language: python
python:
  - "2.7"
  - "3.7"

env:
  global:
      - PYTHONPATH=.

install:
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"

script:
  - "travis_wait 1 python -m unittest discover tests"

after_success:
  - "coverage run -m unittest discover tests"
  - "coveralls"
