language: python
python:
  - 3.6
  - 3.7.9
  - 3.8
  - 3.9

env:
  global:
      - PYTHONPATH=.

install:
  - "pip install coverage==6.2" # https://github.com/nedbat/coveragepy/issues/1310
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"

script:
  - "python -u -m unittest discover -v tests"

after_success:
  - "coverage run --concurrency=thread -m unittest discover -v tests"
  - "coveralls"
