language: python
cache: pip
python:
- 3.7.8
- 3.8
- 3.9
env:
  global:
  - PYTHONPATH=.
install:
- pip install coverage==6.2
- pip install coveralls
- cp packaging/setup.py .
- pip install .
- pip install -r tests/requirements.txt
script:
- python -u -m unittest discover -v tests
after_success:
- coverage run -m unittest discover -v tests
- coveralls
