language: python
cache: pip
python:
- 3.7.8
- '3.8'
- '3.9'
env:
  global:
  - PYTHONPATH=.
install:
- pip install coverage==6.2
- pip install coveralls
- pip install -r tests/requirements.txt
- cp packaging/setup.py .
- pip install .
script:
- python -u -m unittest discover -v tests
after_success:
- coverage run -m unittest discover -v tests
- coveralls
jobs:
  include:
  - name: Python 3.10
    dist: jammy
    python: '3.10'
    before_install:
    - pip install wheel==0.37.1
    - pip install setuptools==45.2.0
  - name: Python 3.11
    dist: jammy
    python: '3.11'
    before_install:
    - pip install --upgrade pip
    - pip install wheel==0.41.2
    - pip install setuptools==65.5.0
