language: python
python:
  - "2.7"
  - "3.6"

env:
  global:
      - PYTHONPATH=.

install:
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"

script:
  - "coverage run -m unittest tests.test_threads.TestThreads.test_interrupt"

after_success:
  - coveralls
