language: python
python:
  - "2.7"
  - "3.6"

env:
  global:
      - PYTHONPATH=.

install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"

script:
  - "python -m unittest discover tests"

